// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __BLE_CONFIG__
#define __BLE_CONFIG__


// Top level macros
#define SILABS_AF_DEVICE_NAME "soc-thunderboard-react"


// Generated plugin macros


// Custom macros
#define RD_0057_0101  1

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE RD_0057_0101


#endif // __BLE_CONFIG__
