// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_software_revision_string         20
#define gattdb_firmware_revision_string         22
#define gattdb_system_id                       24
#define gattdb_battery_measurement             27
#define gattdb_cycling_speed_measurement         31
#define gattdb_cycling_speed_cp                36
#define gattdb_aio_digital_in                  40
#define gattdb_aio_digital_out                 45
#define gattdb_es_humidity                     50
#define gattdb_es_temperature                  52
#define gattdb_es_uvindex                      54
#define gattdb_ota_control                     57
#define gattdb_amblight_lux                    60
#define gattdb_accor_acceleration              63
#define gattdb_accor_orientation               66
#define gattdb_accor_cp                        69

#endif
