// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_system_id                       22
#define gattdb_battery_measurement             25
#define gattdb_cycling_speed_measurement         29
#define gattdb_cycling_speed_cp                34
#define gattdb_aio_digital_in                  38
#define gattdb_aio_digital_out                 43
#define gattdb_es_humidity                     48
#define gattdb_es_temperature                  50
#define gattdb_es_uvindex                      52
#define gattdb_ota_control                     55
#define gattdb_amblight_lux                    58
#define gattdb_accor_acceleration              61
#define gattdb_accor_orientation               64
#define gattdb_accor_cp                        67

#endif
