// Copyright 2018 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_system_id                       18
#define gattdb_battery_measurement             21
#define gattdb_cycling_speed_measurement         25
#define gattdb_cycling_speed_cp                30
#define gattdb_aio_digital_in                  34
#define gattdb_aio_digital_out                 39
#define gattdb_es_humidity                     44
#define gattdb_es_temperature                  46
#define gattdb_es_uvindex                      48
#define gattdb_amblight_lux                    51
#define gattdb_accor_acceleration              54
#define gattdb_accor_orientation               57
#define gattdb_accor_cp                        60

#endif
