/***************************************************************************//**
 * @file
 * @brief hal-config.h
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "board_features.h"
#include "hal-config-app-common.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE              (HAL_CLK_HFCLK_SOURCE_HFXO)
#define HAL_CLK_LFBCLK_SOURCE             (HAL_CLK_LFCLK_SOURCE_LFXO)
#define BSP_CLK_LFXO_PRESENT              (1)
#define BSP_CLK_HFXO_PRESENT              (1)
#define BSP_CLK_LFXO_INIT                  CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_FREQ                 (32768)
#define HAL_CLK_LFACLK_SOURCE             (HAL_CLK_LFCLK_SOURCE_LFXO)
#define BSP_CLK_HFXO_FREQ                 (38400000)
#define BSP_CLK_HFXO_CTUNE                (322)
#define BSP_CLK_HFXO_INIT                  CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_CTUNE_TOKEN          (0)
#define HAL_CLK_HFXO_AUTOSTART            (HAL_CLK_HFXO_AUTOSTART_SELECT)
// [CMU]$

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[DCDC]
#define BSP_DCDC_PRESENT                  (1)

#define HAL_DCDC_BYPASS                   (0)
#define BSP_DCDC_INIT                      EMU_DCDCINIT_DEFAULT
// [DCDC]$

// $[EMU]
#define HAL_EMU_ENABLE                    (1)

// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2CSENSOR]
#ifndef HAL_I2CSENSOR_ENABLE
#define HAL_I2CSENSOR_ENABLE              (0)
#endif
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[FEM]
// [FEM]$

// $[PA]
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
#define PORTIO_PTI_DFRAME_PIN             (13)
#define PORTIO_PTI_DFRAME_PORT            (gpioPortB)
#define PORTIO_PTI_DFRAME_LOC             (6)

#define PORTIO_PTI_DOUT_PIN               (4)
#define PORTIO_PTI_DOUT_PORT              (gpioPortA)
#define PORTIO_PTI_DOUT_LOC               (3)

#define BSP_PTI_DFRAME_PIN                (13)
#define BSP_PTI_DFRAME_PORT               (gpioPortB)
#define BSP_PTI_DFRAME_LOC                (6)

#define BSP_PTI_DOUT_PIN                  (4)
#define BSP_PTI_DOUT_PORT                 (gpioPortA)
#define BSP_PTI_DOUT_LOC                  (3)
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
// [SERIAL]$

// $[SPIDISPLAY]
#ifndef HAL_SPIDISPLAY_ENABLE
#define HAL_SPIDISPLAY_ENABLE             (0)
#endif
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
// [USART0]$

// $[USART1]
// [USART1]$

// $[VCOM]
#ifndef HAL_VCOM_ENABLE
#define HAL_VCOM_ENABLE                   (0)
#endif
// [VCOM]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

// $[Custom pin names]
#define LED_B_PIN                         (2)
#define LED_B_PORT                        (gpioPortA)

#define BTN0_PIN                          (3)
#define BTN0_PORT                         (gpioPortA)

#define PTI_DATA_PIN                      (4)
#define PTI_DATA_PORT                     (gpioPortA)

#define HALL_PWR_PIN                      (11)
#define HALL_PWR_PORT                     (gpioPortB)

#define PTI_SYNC_PIN                      (13)
#define PTI_SYNC_PORT                     (gpioPortB)

#define FLASH_MOSI_PIN                    (6)
#define FLASH_MOSI_PORT                   (gpioPortC)

#define FLASH_MISO_PIN                    (7)
#define FLASH_MISO_PORT                   (gpioPortC)

#define FLASH_CLK_PIN                     (8)
#define FLASH_CLK_PORT                    (gpioPortC)

#define FLASH_CS_PIN                      (9)
#define FLASH_CS_PORT                     (gpioPortC)

#define I2C_SCL_PIN                       (10)
#define I2C_SCL_PORT                      (gpioPortC)

#define I2C_SDA_PIN                       (11)
#define I2C_SDA_PORT                      (gpioPortC)

#define SWCLK_PIN                         (0)
#define SWCLK_PORT                        (gpioPortF)

#define SWDIO_PIN                         (1)
#define SWDIO_PORT                        (gpioPortF)

#define HALL_PIN                          (3)
#define HALL_PORT                         (gpioPortF)

#define ACCEL_INT_PIN                     (4)
#define ACCEL_INT_PORT                    (gpioPortF)

#define LIGHT_INT_PIN                     (5)
#define LIGHT_INT_PORT                    (gpioPortF)

#define LED_G_PIN                         (6)
#define LED_G_PORT                        (gpioPortF)

#define BTN1_PIN                          (7)
#define BTN1_PORT                         (gpioPortF)

// [Custom pin names]$

#endif /* HAL_CONFIG_H */
